// <auto-generated />
using System;
using APBDCW07.Infrastrucutre;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBDCW07.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBDCW07.Models.ComponentManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTC",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NVDA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        });
                });

            modelBuilder.Entity("APBDCW07.Models.ComponentTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            FullName = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            FullName = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            FullName = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("APBDCW07.Models.Components", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU-INT-01",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "Procesor 20-rdzeniowy, taktowanie do 5.6 GHz.",
                            Name = "Intel Core i7-14700K"
                        },
                        new
                        {
                            Code = "GPU-NVD-02",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "Karta graficzna z 12GB pamięci GDDR6X.",
                            Name = "NVIDIA GeForce RTX 4070 Ti"
                        },
                        new
                        {
                            Code = "RAM-AMD-03",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "Pamięć RAM zoptymalizowana pod procesory AMD.",
                            Name = "AMD Expo DDR5 32GB"
                        });
                });

            modelBuilder.Entity("APBDCW07.Models.PCComponents", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU-INT-01",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "GPU-NVD-02",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM-AMD-03",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("APBDCW07.Models.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasMaxLength(5)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biurowy Standard",
                            Stock = 15,
                            Warranty = 24,
                            Weight = 7.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bestia Gamingowa X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.3f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mini PC Home",
                            Stock = 50,
                            Warranty = 12,
                            Weight = 1.8f
                        });
                });

            modelBuilder.Entity("APBDCW07.Models.Components", b =>
                {
                    b.HasOne("APBDCW07.Models.ComponentManufacturers", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDCW07.Models.ComponentTypes", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("APBDCW07.Models.PCComponents", b =>
                {
                    b.HasOne("APBDCW07.Models.Components", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDCW07.Models.PCs", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("APBDCW07.Models.ComponentManufacturers", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBDCW07.Models.ComponentTypes", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBDCW07.Models.Components", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("APBDCW07.Models.PCs", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
